<a href="https://colab.research.google.com/github/DevzsJhonny/Colab_notebooks/blob/main/Casos_de_Dengue_no_Brasil_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Série Histórica - Casos de Dengue notificados em 2022

In [ ]:
##planilha consultada através do link: https://mosquito.saude.es.gov.br/planilhasegraficos

In [2]:
import pandas as pd

dados = pd.read_excel('/content/Planilhas casos notificados arboviroses SE 18_ 2022 (1).xlsx')
dados

,MUNICÍPIO,SRS,SE 1,SE 2,SE 3,SE 4,SE 5,SE 6,SE 7,SE 8,...,SE 46,SE 47,SE 48,SE 49,SE 50,SE 51,SE 52,TOTAL,Nº HABITANTES,INCIDÊNCIA
0,ÁGUIA BRANCA,C,0,1,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,9631,31.149413
1,ALTO RIO NOVO,C,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,7874,12.700025
2,BAIXO GUANDU,C,0,0,1,0,2,1,0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,62,31132,199.151998
3,COLATINA,C,2,2,3,2,3,1,7,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,196,123400,158.833063
4,GOVERNADOR LINDEMBERG,C,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,12880,7.763975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,PRESIDENTE KENNEDY,S,0,0,0,1,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,11658,8.577801
75,RIO NOVO DO SUL,S,0,0,0,1,0,0,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,11626,34.405643
76,SÃO JOSE DO CALÇADO,S,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,10546,9.482268
77,VARGEM ALTA,S,0,0,0,0,0,0,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,21591,0.000000
78,TOTAL,NaN,224,275,215,175,138,163,159,196,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6454,4064052,158.807023