<a href="https://colab.research.google.com/github/DevzsJhonny/Colab_notebooks/blob/main/Produ%C3%A7%C3%A3o_Hospitalar_Desafio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analisando Dados da Saúde - Dados de Produção Hospitalar

In [2]:
# Dados extraídos do DATASUS

In [3]:
import pandas as pd

In [38]:
#dados = pd.read_csv('A150850189_28_143_208 (1).csv', encoding='ISO-8859-1', skiprows=3, sep=';',  thousands='.', decimal=',')

## desafio fiap, mostrar a coluna mais recente do arquivo
dados = pd.read_csv('/content/A152918189_28_143_208.csv', encoding='ISO-8859-1', skiprows=3, sep=';',  thousands='.', decimal=',')

In [39]:
dados.head() #coluna mais recente é do mês Setembro de 2021

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2021/Jan,2021/Fev,2021/Mar,2021/Abr,2021/Mai,2021/Jun,2021/Jul,2021/Ago,2021/Set,Total
0,11 Rondônia,1388528.39,2931283.42,1541682.52,1525314.96,1645953.84,1406150.68,3065279.01,3231494.61,3117178.63,...,9858841.18,9806315.07,14946369.28,15552930.66,16269008.71,15380532.08,14228814.25,12427865.05,"10345616,78",1088059702.25
1,12 Acre,902416.00,1497206.26,1794028.48,1730469.42,1819443.92,1828496.00,2511754.59,2089107.14,2275708.53,...,3715723.12,3538427.92,4077045.92,6307616.67,6354514.15,3461663.11,4979239.30,4138751.64,-,475290315.34
2,13 Amazonas,4735529.42,7118990.57,8196635.49,8259378.42,7831399.90,8477273.62,9368858.72,9352532.70,9363099.35,...,21621697.26,26163677.75,23445832.76,23154039.32,26127701.15,26447055.27,24457791.81,22731356.54,"19840265,30",2061943006.93
3,14 Roraima,657889.53,777939.31,718688.03,839994.39,862347.96,832440.66,996693.09,894271.18,910424.17,...,3266928.47,3519773.73,4437161.10,5171370.92,4266254.94,3103979.88,3743330.65,3781921.16,"3150835,05",352546288.71
4,15 Pará,18864744.11,19553758.20,21937342.70,20842829.69,23249952.88,23240687.56,24002223.56,23341218.03,25172261.32,...,38813794.18,39251569.26,40639703.77,46608262.09,55310881.51,48215050.10,45801750.84,43262884.30,"14569318,55",4968811817.17

In [43]:
pd.options.display.float_format = "{:.2f}".format #notação python

In [49]:
dados.columns

Index(['Unidade da Federação', '2008/Jan', '2008/Fev', '2008/Mar', '2008/Abr',
       '2008/Mai', '2008/Jun', '2008/Jul', '2008/Ago', '2008/Set',
       ...
       '2021/Jan', '2021/Fev', '2021/Mar', '2021/Abr', '2021/Mai', '2021/Jun',
       '2021/Jul', '2021/Ago', '2021/Set', 'Total'],
      dtype='object', length=167)

In [61]:
dados.get("2021/Set") #mostra todos os valores da coluna de Setembro (mais atual)

0       10345616,78
1                 -
2       19840265,30
3        3150835,05
4       14569318,55
5        5032883,11
6         773480,42
7       36250671,51
8       20752326,97
9       75197971,95
10      24063936,32
11      24377900,38
12      83993757,90
13      19758417,78
14      12133818,13
15      99862227,64
16     193773519,61
17      38395547,28
18     128586740,23
19     393119442,09
20     121946453,33
21      83493556,56
22     120016574,60
23      32338424,49
24      27274369,25
25      64176809,02
26      28509985,96
27    1681734850,21
28              NaN
29              NaN
30              NaN
31              NaN
32              NaN
33              NaN
34              NaN
Name: 2021/Set, dtype: object

In [76]:
dados.iloc[:, -1]

0      1088059702.25
1       475290315.34
2      2061943006.93
3       352546288.71
4      4968811817.17
5       337181964.14
6      1110344733.46
7      4161325769.23
8      2450508593.82
9      7118540187.61
10     2867428082.03
11     2796673182.96
12     9243658123.01
13     2394793268.76
14     1313873341.39
15    10498497979.38
16    21899546392.60
17     3710941856.86
18    11131869791.16
19    44290985780.46
20    15672157558.11
21     8392938841.37
22    13613341350.00
23     2516383489.01
24     2386584382.72
25     5380180598.64
26     2778456616.77
27   185012863013.89
28               NaN
29               NaN
30               NaN
31               NaN
32               NaN
33               NaN
34               NaN
Name: Total, dtype: float64